# Generated by Django 4.2.5 on 2023-09-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListXlsx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('driveId', models.CharField(max_length=150)),
                ('modDate', models.DateField()),
                ('img', models.ImageField(upload_to='media/img/artics/')),
                ('pathlocal', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ListDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filrId', models.CharField(max_length=50)),
                ('parenId', models.CharField(max_length=50)),
                ('listXlsxID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listxlsx')),
            ],
        ),
        migrations.CreateModel(
            name='Artic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('priceMa', models.FloatField()),
                ('priceMi', models.FloatField()),
                ('listXlsxID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listxlsx')),
            ],
        ),
    ]
