# Generated by Django 4.2.5 on 2023-09-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('priceMa', models.FloatField()),
                ('priceMi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaXlsx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('locaRute', models.FilePathField(max_length=750)),
                ('driveId', models.CharField(max_length=150)),
                ('modDate', models.DateField()),
                ('img', models.ImageField(upload_to='media/img/artics/')),
                ('artics', models.CharField(max_length=5000)),
                ('pathXlsx', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
