# Generated by Django 4.2.5 on 2023-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listxlsx',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/artics/'),
        ),
    ]
