# Generated by Django 4.2.5 on 2023-09-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaxlsx',
            old_name='pathXlsx',
            new_name='pathlocal',
        ),
        migrations.RemoveField(
            model_name='listaxlsx',
            name='locaRute',
        ),
    ]
