# Generated by Django 4.2.5 on 2023-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_listxlsx_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listxlsx',
            old_name='pathlocal',
            new_name='pathLocal',
        ),
        migrations.AlterField(
            model_name='listxlsx',
            name='driveId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
