# Generated by Django 4.2.5 on 2023-09-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_modelo_test_moddate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modelo_test',
        ),
        migrations.AlterField(
            model_name='listxlsx',
            name='modDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listxlsx',
            name='pathLocal',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
