# Generated by Django 4.2.5 on 2023-09-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_pathlocal_listxlsx_pathlocal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listxlsx',
            old_name='name',
            new_name='name_file',
        ),
    ]
