# Generated by Django 4.2.5 on 2023-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_artic_modelartic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modellistxlsx',
            old_name='name_file',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='modellistxlsx',
            name='modDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='modellistxlsx',
            name='pathLocal',
            field=models.CharField(default='', max_length=500),
        ),
    ]
