# Generated by Django 4.2.6 on 2023-10-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_modellistxlsx_parentma_modellistxlsx_parentmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modellistxlsx',
            name='parentMa',
        ),
        migrations.RemoveField(
            model_name='modellistxlsx',
            name='parentMi',
        ),
    ]
