# Generated by Django 5.0 on 2024-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
