# Generated by Django 4.2.5 on 2023-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_test',
            name='modDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo_test',
            name='pathLocal',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
