# Generated by Django 4.2.5 on 2023-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_file_modellistxlsx_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='modelartic',
            index=models.Index(fields=['code'], name='core_modela_code_5d85b3_idx'),
        ),
    ]
