# Generated by Django 4.2.5 on 2023-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelartic_core_modela_code_5d85b3_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='modelartic',
            name='core_modela_code_5d85b3_idx',
        ),
        migrations.AddIndex(
            model_name='modelartic',
            index=models.Index(fields=['code', 'listXlsxID'], name='core_modela_code_733a61_idx'),
        ),
    ]
