# Generated by Django 4.2.5 on 2023-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_modelartic_core_modela_code_5d85b3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelartic',
            name='col',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modelartic',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
