# Generated by Django 4.2.5 on 2023-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelartic_col_modelartic_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartic',
            name='col',
            field=models.CharField(default='', max_length=1),
        ),
    ]
