# Generated by Django 4.2.5 on 2023-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_modelartic_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartic',
            name='col',
            field=models.IntegerField(default=0),
        ),
    ]
