# Generated by Django 4.2.5 on 2023-10-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_modelartic_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelToUpdateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsxId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modellistxlsx')),
            ],
        ),
    ]
