# Generated by Django 4.2.5 on 2023-10-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_modelfiledrive_modelfolderdrive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfiledrive',
            name='parentMaId',
        ),
        migrations.RemoveField(
            model_name='modelfiledrive',
            name='parentMiId',
        ),
        migrations.RemoveField(
            model_name='modelfiledrive',
            name='parentOrderMaId',
        ),
        migrations.RemoveField(
            model_name='modelfiledrive',
            name='parentOrderMiId',
        ),
        migrations.AddField(
            model_name='modelfiledrive',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelfolderdrive'),
        ),
        migrations.AddField(
            model_name='modelfolderdrive',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelfolderdrive'),
        ),
    ]
