# Generated by Django 4.2.5 on 2023-10-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_modelfiledrive_parentmaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfolderdrive',
            name='parentId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelfolderdrive'),
        ),
    ]
