# Generated by Django 4.2.6 on 2023-10-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_modelfiledrive_parentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellistxlsx',
            name='parentMa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foder_ma', to='core.modelfolderdrive'),
        ),
        migrations.AddField(
            model_name='modellistxlsx',
            name='parentMi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foder_mi', to='core.modelfolderdrive'),
        ),
    ]
