# Generated by Django 4.2.5 on 2023-11-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_modellistxlsx_parentma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUploadingDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.BooleanField(default=False)),
                ('fileDrive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelfolderdrive')),
            ],
        ),
    ]
