# Generated by Django 4.2.7 on 2023-11-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_modeluploadingdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelartic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
