# Generated by Django 4.2.7 on 2023-11-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_modeluploaddrive_delete_modeluploadingdrive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelUploadDrive',
            new_name='ModelToUploadDrive',
        ),
    ]
