# Generated by Django 4.2.7 on 2023-11-24 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_modeluploaddrive_modeltouploaddrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltouploaddrive',
            name='fileDrive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelfiledrive'),
        ),
    ]
